import { Product, Banner } from '@/types'

export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'Premium Toor Dal',
    slug: 'premium-toor-dal',
    description: 'High-quality toor dal sourced from the finest farms. Rich in protein and essential nutrients. Perfect for making dal tadka, sambar, and other traditional dishes.',
    shortDescription: 'Premium quality toor dal, rich in protein',
    category: 'pulses',
    images: [
      '/products/toor-dal.jpg',
      '/products/toor-dal.jpg',
    ],
    variants: [
      {
        id: 'v1',
        weight: '500',
        unit: 'g',
        price: 120,
        mrp: 150,
        discount: 20,
        sku: 'TD-500',
        stock: 100,
        isDefault: true,
      },
      {
        id: 'v2',
        weight: '1',
        unit: 'kg',
        price: 220,
        mrp: 280,
        discount: 21,
        sku: 'TD-1000',
        stock: 80,
      },
      {
        id: 'v3',
        weight: '5',
        unit: 'kg',
        price: 1000,
        mrp: 1300,
        discount: 23,
        sku: 'TD-5000',
        stock: 30,
      },
    ],
    nutrition: {
      servingSize: '100g',
      calories: 335,
      protein: '22g',
      carbs: '60g',
      fat: '1.5g',
      fiber: '15g',
    },
    features: [
      'No artificial colors',
      'No preservatives',
      'Farm fresh',
      'Rich in protein',
      'Easy to cook',
    ],
    tags: ['dal', 'pulses', 'protein', 'vegetarian'],
    rating: 4.5,
    reviewCount: 234,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    stock: 210,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: '2',
    name: 'Premium Cashews (Kaju)',
    slug: 'premium-cashews-kaju',
    description: 'Whole cashew nuts, carefully selected and packed. Rich, creamy texture perfect for snacking or cooking. Sourced from Kerala farms.',
    shortDescription: 'Premium whole cashews from Kerala',
    category: 'dry-fruits',
    images: [
      '/products/cashews.jpg',
      '/products/cashews.jpg',
    ],
    variants: [
      {
        id: 'v1',
        weight: '250',
        unit: 'g',
        price: 280,
        mrp: 350,
        discount: 20,
        sku: 'CF-250',
        stock: 50,
        isDefault: true,
      },
      {
        id: 'v2',
        weight: '500',
        unit: 'g',
        price: 540,
        mrp: 680,
        discount: 21,
        sku: 'CF-500',
        stock: 40,
      },
      {
        id: 'v3',
        weight: '1',
        unit: 'kg',
        price: 1050,
        mrp: 1350,
        discount: 22,
        sku: 'CF-1000',
        stock: 25,
      },
    ],
    nutrition: {
      servingSize: '100g',
      calories: 553,
      protein: '18g',
      carbs: '30g',
      fat: '44g',
      fiber: '3g',
    },
    features: [
      'Whole cashews',
      'No broken pieces',
      'Fresh and crunchy',
      'Rich in minerals',
      'Premium quality',
    ],
    tags: ['cashew', 'dry-fruits', 'nuts', 'healthy'],
    rating: 4.8,
    reviewCount: 456,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    stock: 115,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-03-18'),
  },
  {
    id: '3',
    name: 'Organic Turmeric Powder',
    slug: 'organic-turmeric-powder',
    description: 'Pure organic turmeric powder with high curcumin content. Freshly ground from premium turmeric roots. No additives or artificial colors.',
    shortDescription: 'Pure organic turmeric powder',
    category: 'masala',
    images: [
      '/products/turmeric-powder.jpg',
      '/products/turmeric-powder.jpg',
    ],
    variants: [
      {
        id: 'v1',
        weight: '100',
        unit: 'g',
        price: 45,
        mrp: 60,
        discount: 25,
        sku: 'TP-100',
        stock: 200,
        isDefault: true,
      },
      {
        id: 'v2',
        weight: '250',
        unit: 'g',
        price: 100,
        mrp: 140,
        discount: 29,
        sku: 'TP-250',
        stock: 150,
      },
      {
        id: 'v3',
        weight: '500',
        unit: 'g',
        price: 190,
        mrp: 270,
        discount: 30,
        sku: 'TP-500',
        stock: 100,
      },
    ],
    nutrition: {
      servingSize: '1 tsp (5g)',
      calories: 15,
      protein: '0.5g',
      carbs: '3g',
      fat: '0.3g',
      fiber: '1g',
    },
    features: [
      'Organic certified',
      'High curcumin',
      'No artificial colors',
      'Freshly ground',
      'Anti-inflammatory',
    ],
    tags: ['turmeric', 'masala', 'organic', 'spices'],
    rating: 4.7,
    reviewCount: 189,
    isFeatured: true,
    isNew: true,
    isBestSeller: false,
    stock: 450,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: '4',
    name: 'Kashmiri Red Chilli Powder',
    slug: 'kashmiri-red-chilli-powder',
    description: 'Authentic Kashmiri red chilli powder known for its vibrant color and mild heat. Perfect for adding color to your dishes without excessive spiciness.',
    shortDescription: 'Vibrant color, mild heat chilli powder',
    category: 'masala',
    images: [
      '/products/red-chilli-powder.jpg',
      '/products/red-chilli-powder.jpg',
    ],
    variants: [
      {
        id: 'v1',
        weight: '100',
        unit: 'g',
        price: 55,
        mrp: 75,
        discount: 27,
        sku: 'KCP-100',
        stock: 180,
        isDefault: true,
      },
      {
        id: 'v2',
        weight: '250',
        unit: 'g',
        price: 125,
        mrp: 175,
        discount: 29,
        sku: 'KCP-250',
        stock: 120,
      },
      {
        id: 'v3',
        weight: '500',
        unit: 'g',
        price: 230,
        mrp: 330,
        discount: 30,
        sku: 'KCP-500',
        stock: 80,
      },
    ],
    features: [
      'Authentic Kashmiri',
      'Vibrant red color',
      'Mild heat level',
      'No artificial colors',
      'Premium quality',
    ],
    tags: ['chilli', 'masala', 'kashmiri', 'spices'],
    rating: 4.6,
    reviewCount: 312,
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
    stock: 380,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: '5',
    name: 'Premium Almonds (Badam)',
    slug: 'premium-almonds-badam',
    description: 'California almonds, rich in vitamin E and healthy fats. Perfect for snacking, milk, or adding to desserts. Carefully selected for quality.',
    shortDescription: 'Premium California almonds',
    category: 'dry-fruits',
    images: [
      '/products/almonds.jpg',
      '/products/almonds.jpg',
    ],
    variants: [
      {
        id: 'v1',
        weight: '250',
        unit: 'g',
        price: 220,
        mrp: 280,
        discount: 21,
        sku: 'AL-250',
        stock: 90,
        isDefault: true,
      },
      {
        id: 'v2',
        weight: '500',
        unit: 'g',
        price: 420,
        mrp: 540,
        discount: 22,
        sku: 'AL-500',
        stock: 70,
      },
      {
        id: 'v3',
        weight: '1',
        unit: 'kg',
        price: 800,
        mrp: 1050,
        discount: 24,
        sku: 'AL-1000',
        stock: 40,
      },
    ],
    nutrition: {
      servingSize: '100g',
      calories: 579,
      protein: '21g',
      carbs: '22g',
      fat: '50g',
      fiber: '12g',
    },
    features: [
      'California almonds',
      'Rich in vitamin E',
      'Heart healthy',
      'Premium quality',
      'Fresh and crunchy',
    ],
    tags: ['almonds', 'dry-fruits', 'nuts', 'healthy'],
    rating: 4.7,
    reviewCount: 523,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    stock: 200,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-03-19'),
  },
  {
    id: '6',
    name: 'Garam Masala Powder',
    slug: 'garam-masala-powder',
    description: 'Traditional blend of aromatic spices including cardamom, cinnamon, cloves, and more. Freshly ground for maximum flavor and aroma.',
    shortDescription: 'Traditional aromatic spice blend',
    category: 'masala',
    images: [
      '/products/garam-masala.jpg',
      '/products/garam-masala.jpg',
    ],
    variants: [
      {
        id: 'v1',
        weight: '50',
        unit: 'g',
        price: 40,
        mrp: 55,
        discount: 27,
        sku: 'GM-50',
        stock: 150,
        isDefault: true,
      },
      {
        id: 'v2',
        weight: '100',
        unit: 'g',
        price: 75,
        mrp: 105,
        discount: 29,
        sku: 'GM-100',
        stock: 120,
      },
      {
        id: 'v3',
        weight: '250',
        unit: 'g',
        price: 175,
        mrp: 250,
        discount: 30,
        sku: 'GM-250',
        stock: 80,
      },
    ],
    features: [
      'Traditional recipe',
      'Freshly ground',
      'Aromatic blend',
      'No preservatives',
      'Premium spices',
    ],
    tags: ['garam-masala', 'masala', 'spices', 'blend'],
    rating: 4.8,
    reviewCount: 267,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    stock: 350,
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-03-17'),
  },
]

export const sampleBanners: Banner[] = [
  {
    id: '1',
    title: 'Premium Dry Fruits',
    subtitle: 'Flat 25% OFF on all dry fruits',
    image: '/banners/dry-fruits-banner.jpg',
    mobileImage: '/banners/dry-fruits-banner-mobile.jpg',
    link: '/products?category=dry-fruits',
    buttonText: 'Shop Now',
    order: 1,
    isActive: true,
  },
  {
    id: '2',
    title: 'Fresh Masala Powders',
    subtitle: 'Authentic taste, premium quality',
    image: '/banners/masala-banner.jpg',
    mobileImage: '/banners/masala-banner-mobile.jpg',
    link: '/products?category=masala',
    buttonText: 'Explore',
    order: 2,
    isActive: true,
  },
  {
    id: '3',
    title: 'Premium Pulses & Dal',
    subtitle: 'Farm fresh, protein rich',
    image: '/banners/pulses-banner.jpg',
    mobileImage: '/banners/pulses-banner-mobile.jpg',
    link: '/products?category=pulses',
    buttonText: 'Buy Now',
    order: 3,
    isActive: true,
  },
]
